#############################
#                           #
# viper web server 配置文件 #
#                           #
#############################


########## 环境配置
env = "dev"

########## server 相关配置
[server]
# server 运行地址，支持 HTTP 端口 ":port" 或 UNIX Socket "unix:/file"
addr = ":4869"
# gin mode ，可选值： debug 、 test 、 release
mode = "debug"
# 开启 pprof
pprof = true
# 请求处理超时时间（秒）
handler_timeout = 5
# 开启 prometheus metrics
metrics = true
# 开启 ratelimiter 请求频率限制
ratelimiter = false

########## token bucket 请求频率限制配置
[ratelimiter]
# 限频方式： mem->进程内存； redis.<WHICH>->使用用配置文件中对应的 redis 配置，如 redis.localhost
type = "mem"
# 速率限制：每隔多少微秒填充 1 个 token
bucket_fill_every_microsecond = 1000000
# 允许的最大突增量： bucket 容量
bucket_capacity = 1
# bucket 过期时间（秒）
bucket_expire_second = 3600

########## 日志相关配置
[logging]
# 日志级别，可选值： debug info warn error dpanic panic fatal
level = "debug"
# 日志格式，可选值： json console
format = "json"
# 日志输出路径
output_paths = ["stdout"]
# 是否关闭打印 caller 字段
disable_caller = false
# 是否关闭打印 stacktrace 字段
disable_stacktrace = true
## 动态修改日志级别 http 服务配置
[logging.atomic_level_server]
# http 服务端口
addr = ":4870"
# 接口 url path
path = "/"

## 访问日志相关配置
[logging.access_logger]
# 打印更多访问信息字段
enable_details = false
# 打印 context 中的 keys 信息，慎用，推荐仅开发调试使用
enable_context_keys = false
# 打印请求 Header ，慎用，推荐仅开发调试使用
enable_request_header = false
# 打印请求的表单信息，慎用，推荐仅开发调试使用
enable_request_form = false
# 打印请求 body ，慎用，严重影响性能
enable_request_body = false
# 打印响应 body ，慎用，严重影响性能
enable_response_body = false
# 精确指定不打印日志的 path
skip_paths = []
# 正则表达式指定不打印日志的 path
skip_path_regexps = [
    "/x/apidocs/.+\\.json",
    "/x/apidocs/.+\\.js",
    "/x/apidocs/.+\\.css",
]

########## sentry 相关配置
[sentry]
# sentry dsn
dsn = ""
debug = true

########## apidocs 相关配置
[apidocs]
# 文档标题
title = "pink-lady swagger apidocs"
# 文档描述
desc = "Using pink-lady to develop gin app on fly."
# 请求地址，端口要和 server.addr 一致，浏览器访问时需要区分 127.0.0.1 和 localhost
host = "localhost:4869"
# 请求地址的 basepath
basepath = "/"
# 支持的请求 schemes
schemes = ["http"]

########## basic auth 相关配置
[basic_auth]
# 登录用户名
username = "admin"
# 登录密码
password = "admin"

########## MySQL 相关配置
# mysql 按不同环境可以添加多个配置
# 本地配置
[mysql.localhost]
host = "localhost"
port = 3306
username = "root"
password = "roooooot"
dbname = "test"
log_mode = false
max_idle_conns = 20
max_open_conns = 20
conn_max_life_minutes = 10
conn_timeout = 3
read_timeout = 5
write_timeout = 5
# 其他环境
[mysql.other]

########## SQLite3 相关配置
[sqlite3.dev]
dbname = "sqlite3.dev.db"
log_mode = false

########## Postgres 相关配置
[postgres.localhost]
host = "localhost"
port = 5432
username = "root"
password = "roooooot"
dbname = "test"
log_mode = false
max_idle_conns = 20
max_open_conns = 20
conn_max_life_minutes = 10
disable_ssl = true

########## Sqlserver 相关配置
[sqlserver.localhost]
host = "localhost"
port = 1433
username = "root"
password = "roooooot"
dbname = "test"
log_mode = false
max_idle_conns = 20
max_open_conns = 20
conn_max_life_minutes = 10

########## Redis 相关配置
# redis 按不同环境可以添加多个配置
# 本地配置
[redis.localhost]
# redis 地址
addr = "localhost:6379"
# 密码
password = ""
# 使用的 db 索引
db = 0
# 连接超时时间（秒）
dial_timeout = 5
# 读超时（秒）
read_timeout = 3
# 写超时（秒）
write_timeout = 3
# 连接池大小: 0表示10 * runtime.NumCPU()
pool_size = 0
[redis.other]

########## Redis Sentinel 相关配置
[redis.sentinel.prod]
# master 节点名
master_name = ""
# sentinel 地址列表
sentinel_addrs = [""]
# 密码
password = ""
# db 索引
db = 0
# 连接超时时间（秒）
dial_timeout = 5
# 读超时（秒）
read_timeout = 3
# 写超时（秒）
write_timeout = 3
# 连接池大小: 0表示10 * runtime.NumCPU()
pool_size = 0

########## Redis Cluster 相关配置
[redis.cluster.prod]
# 集群节点地址列表
addrs = [""]
# 密码
password = ""
# 读超时（秒）
read_timeout = 3
# 写超时（秒）
write_timeout = 3
